# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Mapbox Downloads Secret Token (specify MAPBOX_DOWNLOADS_TOKEN in local.properties or ~/.gradle/gradle.properties)

# Allow APK to be installed directly on other devices without ADB/Test-Only restriction
android.injected.testOnly=false
